package com.i2icellcelly.DGW.Business;

import com.i2icellcelly.DGW.Entities.AkkaTrafficSenderActor;
import com.i2icellcelly.DGW.Entities.DGWMessage;

import org.json.simple.JSONObject;

/**
 * Routes the traffic that is generated by the simulator to the OCS. The messages that are sent by the
 * simulator are parsed, reformatted, and finally the Partition Keys to be used for faster VoltDB queries
 * are added to the final message that will be sent to the OCS.
 */
public interface ITrafficService {
    /**
     * Sends a DGWMessage to the OCS.
     * Requires a valid JSON object to be sent to the generateMessage method.
     * The function does not modify the JSON object during its operations.
     * The message is sent to the OCS via the Akka actor after its creation.
     *
     * @param message  A valid JSON object that includes the necessary information
     *                 for the OCS calculations such as the MSISDN and the usage amount.
     * @see ITrafficService
     * @see AkkaTrafficSenderActor
     * @see DGWMessage
     */
    void generateTraffic(JSONObject message);
}
